### ISSUE TITLE
Should use weights_only with torch.load

### ISSUE THREAD

**Issue by kit1980** [johnma2006/mamba-minimal#1]
`torch.load` without `weights_only` is a potential security issue:
https://github.com/johnma2006/mamba-minimal/blob/a2a47e0efcd44902d78efa022e1c81504037f0a5/model.py#L117

Found using https://github.com/pytorch-labs/torchfix:
 
 > model.py:117:20: TOR102 [*] `torch.load` without `weights_only` parameter is unsafe. Explicitly set `weights_only` to False only if you trust the data you load and full pickle functionality is needed, otherwise set `weights_only=True`.

**Comment by johnma2006** [comment]
Thanks. I changed it: https://github.com/johnma2006/mamba-minimal/commit/82efa90919c3b5066674216f3edcebb3414a7b8f
