### ISSUE TITLE
Does mamba minimal has gpu op optimization

### ISSUE THREAD

**Issue by pengzhangzhi** [johnma2006/mamba-minimal#13]
Hi, thanks for the great work! I would like to know does mamba-minimal has GPU op optimization? It seems to me that it doesn't have.  I want to train a large-scale mamba and am currently considering the original mamba and mamba-minimal.

**Comment by pengzhangzhi** [comment]
My concerns are mainly around the efficiency in training.

**Comment by johnma2006** [comment]
In this case you should definitely be using the official implementation, as
(1) it is heavily optimized, and (2) it has proper initialization.

**Comment by pengzhangzhi** [comment]
thanks!!!
