### ISSUE TITLE
Parameter Initialization

### ISSUE THREAD

**Issue by dashstander** [johnma2006/mamba-minimal#17]
Hey! Thanks so much for putting this together. You mention that the parameter initialization isn't correct, can you point me towards what it _should_ be? I've tried looking at the official repo and didn't see any out-of-the-ordinary stuff.

**Comment by johnma2006** [comment]
So sorry for the late reply! I didn’t look carefully into the official repo’s initialization scheme, so I just assumed that it differed from my repo. But if you noticed they are in fact equal, then I’ll take a closer look in a bit and remove my disclaimer. Thank you!
